//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18063
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Embedded_Resource {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalRes_ua {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalRes_ua() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestFactory.App_LocalResources.GlobalRes.ua", typeof(GlobalRes_ua).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Додати студента.
        /// </summary>
        public static string addStudent {
            get {
                return ResourceManager.GetString("addStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адміністратор.
        /// </summary>
        public static string admin {
            get {
                return ResourceManager.GetString("admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на цінують.
        /// </summary>
        public static string appriciate {
            get {
                return ResourceManager.GetString("appriciate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Авторизація.
        /// </summary>
        public static string authorization {
            get {
                return ResourceManager.GetString("authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Середні оцінки.
        /// </summary>
        public static string averageMarks {
            get {
                return ResourceManager.GetString("averageMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Відмінити.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Близькі типи.
        /// </summary>
        public static string closeTypes {
            get {
                return ResourceManager.GetString("closeTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повернути групу після видалення буде неможливо. Ви дісно хочете її видалити?.
        /// </summary>
        public static string conformationOnDeleteGroup {
            get {
                return ResourceManager.GetString("conformationOnDeleteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повернути сдутента після видалення буде неможливо. Ви дісно хочете його видалити?.
        /// </summary>
        public static string conformationOnDeleteStudent {
            get {
                return ResourceManager.GetString("conformationOnDeleteStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cтворіть групу.
        /// </summary>
        public static string createAction {
            get {
                return ResourceManager.GetString("createAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нова група.
        /// </summary>
        public static string createGroup {
            get {
                return ResourceManager.GetString("createGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Створіть предмет.
        /// </summary>
        public static string createSubject {
            get {
                return ResourceManager.GetString("createSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Видалити.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Видалення.
        /// </summary>
        public static string deleting {
            get {
                return ResourceManager.GetString("deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Детальний опис.
        /// </summary>
        public static string detailedDescription {
            get {
                return ResourceManager.GetString("detailedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завантажити.
        /// </summary>
        public static string download {
            get {
                return ResourceManager.GetString("download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редагувати.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редагуйте групу.
        /// </summary>
        public static string editAction {
            get {
                return ResourceManager.GetString("editAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email редактора .
        /// </summary>
        public static string editorEmail {
            get {
                return ResourceManager.GetString("editorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль редактора.
        /// </summary>
        public static string editorPassword {
            get {
                return ResourceManager.GetString("editorPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введіть логін.
        /// </summary>
        public static string enterLogin {
            get {
                return ResourceManager.GetString("enterLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введіть ім&apos;я студента.
        /// </summary>
        public static string enterNameOfStudent {
            get {
                return ResourceManager.GetString("enterNameOfStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введіть пароль.
        /// </summary>
        public static string enterPassword {
            get {
                return ResourceManager.GetString("enterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вхід.
        /// </summary>
        public static string entry {
            get {
                return ResourceManager.GetString("entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Помилка запиту..
        /// </summary>
        public static string error_400 {
            get {
                return ResourceManager.GetString("error_400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заборонено. Доступ обмежено..
        /// </summary>
        public static string error_403 {
            get {
                return ResourceManager.GetString("error_403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сторінка не знайдена..
        /// </summary>
        public static string error_404 {
            get {
                return ResourceManager.GetString("error_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Помилка сервера..
        /// </summary>
        public static string error_500 {
            get {
                return ResourceManager.GetString("error_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вихід.
        /// </summary>
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Факультет.
        /// </summary>
        public static string faculty {
            get {
                return ResourceManager.GetString("faculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email заповнювача.
        /// </summary>
        public static string fillerEmail {
            get {
                return ResourceManager.GetString("fillerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль заповнювача.
        /// </summary>
        public static string fillerPassword {
            get {
                return ResourceManager.GetString("fillerPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Створити або відредагувати групу з такими ім&apos;ям заборонено .
        /// </summary>
        public static string forbidenAction {
            get {
                return ResourceManager.GetString("forbidenAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Група.
        /// </summary>
        public static string group {
            get {
                return ResourceManager.GetString("group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ідентифікатор групи пустий..
        /// </summary>
        public static string groupIdIsEmpty {
            get {
                return ResourceManager.GetString("groupIdIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Група з таким ім&apos;ям уже існує.
        /// </summary>
        public static string groupIsAlreadyExist {
            get {
                return ResourceManager.GetString("groupIsAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дані введені некоректно.
        /// </summary>
        public static string invalidData {
            get {
                return ResourceManager.GetString("invalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на подобається.
        /// </summary>
        public static string like {
            get {
                return ResourceManager.GetString("like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Увійти.
        /// </summary>
        public static string loginAction {
            get {
                return ResourceManager.GetString("loginAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Довге ім&apos;я.
        /// </summary>
        public static string longName {
            get {
                return ResourceManager.GetString("longName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Характерні особливості.
        /// </summary>
        public static string mainFeatures {
            get {
                return ResourceManager.GetString("mainFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ім&apos;я.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назва предмета.
        /// </summary>
        public static string nameSubject {
            get {
                return ResourceManager.GetString("nameSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на + Новий предмет.
        /// </summary>
        public static string newSubject {
            get {
                return ResourceManager.GetString("newSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У вас немає доступу до даної групи.
        /// </summary>
        public static string noAccessToGroup {
            get {
                return ResourceManager.GetString("noAccessToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У вас відключені Cookie.
        /// </summary>
        public static string offCookie {
            get {
                return ResourceManager.GetString("offCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У вас відключений Javascript.
        /// </summary>
        public static string offJavascript {
            get {
                return ResourceManager.GetString("offJavascript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Протилежний тип.
        /// </summary>
        public static string oppositeType {
            get {
                return ResourceManager.GetString("oppositeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Людям типу.
        /// </summary>
        public static string peopleOfSuchType {
            get {
                return ResourceManager.GetString("peopleOfSuchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Надається перевага професії.
        /// </summary>
        public static string preferredOccupation {
            get {
                return ResourceManager.GetString("preferredOccupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле має бути встановлено.
        /// </summary>
        public static string required {
            get {
                return ResourceManager.GetString("required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле повинно бути заповненим.
        /// </summary>
        public static string requiredField {
            get {
                return ResourceManager.GetString("requiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зберегти.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Коротке ім&apos;я.
        /// </summary>
        public static string shortName {
            get {
                return ResourceManager.GetString("shortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Середньоквадратичне відхилення.
        /// </summary>
        public static string standardDeviationMarks {
            get {
                return ResourceManager.GetString("standardDeviationMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предмети.
        /// </summary>
        public static string subject {
            get {
                return ResourceManager.GetString("subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прізвище.
        /// </summary>
        public static string surname {
            get {
                return ResourceManager.GetString("surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тест Холланда.
        /// </summary>
        public static string testHolland {
            get {
                return ResourceManager.GetString("testHolland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редагуйте предмет.
        /// </summary>
        public static string updateSubject {
            get {
                return ResourceManager.GetString("updateSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рік початку навчання.
        /// </summary>
        public static string yearOfStartingEducation {
            get {
                return ResourceManager.GetString("yearOfStartingEducation", resourceCulture);
            }
        }
    }
}
